apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::376464441015:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-PP5ytXFsslYn
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::376464441015:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-22T20:42:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1259"
  uid: 58c5c5c4-6c0f-415a-b4bb-0631425e43dc
